# Generated by Django 4.2.7 on 2025-07-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_quick_action",
            field=models.BooleanField(
                default=False, help_text="Show this product in Quick Actions section"
            ),
        ),
    ]
